# Generated by Django 3.2.12 on 2022-05-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='tags',
        ),
        migrations.AddField(
            model_name='housetransactioninfo',
            name='use',
            field=models.CharField(help_text='房屋用途', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(help_text='价格，单位元', null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='size',
            field=models.FloatField(help_text='房子大小， 多少平米', null=True),
        ),
    ]
