# Generated by Django 3.2.12 on 2022-05-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0002_auto_20220501_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetransactioninfo',
            name='house',
            field=models.OneToOneField(help_text='房子外键', on_delete=django.db.models.deletion.CASCADE, to='lianjia.house'),
        ),
    ]
