# Generated by Django 3.2.12 on 2022-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0004_auto_20220522_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='unit_price',
            field=models.FloatField(help_text='房子均价', null=True),
        ),
    ]
