# Generated by Django 3.2.12 on 2022-05-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0005_house_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='year',
            field=models.IntegerField(help_text='挂牌时间', max_length=500, null=True),
        ),
    ]
